language: node_js

node_js:
  - "16"

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "fcrKXcKv1xwSOLs0cqRg9xA0wUqpe4aJ+t/FymmTxkewJeeA3yyk0AqqQKRvRxWOV+875ED33TWo2mCT+91+IatNTIt6ZDk+gwIfGDdqCPW2+WHScuI3KnlXEg+RFplpPtRUn8sg7JMcccH6rDF4VURop4RpEeyq4USkGLjdghowfdDpG5b7RVLbRaUoJV3Fsezq0phReKfO1ugDqZ38M1h8W+zCXlBqauC5tE+C28vpwqPgSWjh8mwcy7R8u61Tzx1hBMVwQVWNnyLO/Z9kCnFX5VmIAuIu9DWOm3hOK21OGOLj0TWIjDf8m1YeN2+5Fszj0nljasVWh1GovOqEbQdxyLSPhkSeS/isaCni7aN3xeBdbN/Xqe1UVzYD3BtEOyZwYe0ywzJZZoxrfkrT1lsaViJyoi59m75NCsgNNq9p53Yevj6Li/MrtdtyOvpF3IjjjnKoiZfWFRejXFt45AlaAOv894b3OO98L+nLlHBiBuqt94anGdFL4HmjB8DVG7H5WfyKP5EtYcrs7VSjTTk0KSfMg+f4QDRrapZZydtH8M4rpA5oEUpsfLzRanIoC0jKbidd2FXcJ7dOkOyLxxSWm6bOckgtGWUwX66NGSU3hqx2Kmsee+EuXF0Tkqau1/dqpuQLIErKfKbnM80uf2PurTkDmqSZeITy6YoAZr8="
      
install:
  - npm install

script:
  - npm run test && npm run tslint && sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if you're using this project as a starting point of yours
notifications:
  email: false
  webhooks:
    - secure: "Kz717m4p/AX4RWZxdXW2N+JqNLtdCj1X6Y5CI4tmiWGgxdTBU5lFAQ905dbzku5Hsx6AJdu+b+PpX8ixjkRFDX+CkQ//W5IRUojciLojC5eVRmzYgbhLjmpZmYdc3UvcLTKyHCJLY5GGJ1O0TxjapSJ+1Mp1T1wYsyvcAF55HdFHHOZCy8JIuHQBZmMruMeFDTwmS41cJwqm1fAmKzRESP22fs+njFbsOUVVqiTr0VqxH3h2JJxr5BoLwl17Y8VZ+VYTvPcilAEPeAGhTec6JeEO5SAfuv/6ji2SnCrX29YSt7c20jPAALEPEA3XKepJJPfl+liftbO6mHBobox7z8mx/UyDNqq5e39IShDPzfV2COfb9n/LJc/gxzPYwF1tj8g+V8ArxPqKTv3q9w1A0NVBHGKUlR9/f+WvPoyywT0BApJEOCpk3nSGPuCJC2sR8jSOxZbRgqfLRaZbwZab66+MU3NDqomKBSI49W4WgwWjJ4THkK1wN0f4Z8RWzLt+2Dald5LJmxA1A69piMSKAmqN37kYb6g06DnWlC2SyrUVPrZXrNXdE1NviX/KI+qxEzY3AxXzGjmAgcisuNSEBz2cS/JiotcQQvtlMaELLm0EaHqzaB0oI5sM8gISuWbB6PSSfdrDZouhn8azQti2e0HeWHwuhA18aDOLN3a22xE="
  on_start: always
