name: Test checks
on:
  check_suite:
    type: [completed]
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event_name }}
          cat ${{ github.event_path }}
